// Fixed texts, English. Same keys as ru.js; English is also the source for
// machine translation into other languages (DR15) and the fallback when that
// translation fails.

export default {
  "state.paused": "The bot is paused: new group messages are not stored or processed. Direct chats still work.",
  "state.resume_not_pauser": "Only the person who paused can resume.",
  "state.resumed": "Pause lifted. I'm following the conversation again.",
  "state.revoked": "Consent withdrawn, the bot has stopped. Data is kept but not processed.",
  "state.revoked_partner_dm": "Until consent is restored, I only use our own chat — I'm not using the shared history right now.",
  "state.suspended_third_member": "Someone new joined the group. I've stopped: the shared conversation should stay between the two of you.",
  "state.suspended_not_admin": "I need admin rights to check that only the two of you are in the group. Give them back and I'll continue.",
  "state.restored": "It's just the two of you again. Continuing.",
  "state.stranger_start": "This is a private bot for one couple.",

  "onboarding.admin_request": "I need admin rights to see all messages and check that only the two of you are here. I won't delete or ban anyone.",
  "onboarding.group_intro": "I help you translate and take turns talking. I'll start once each of you agrees.",
  "onboarding.open_bot_button": "{name} → open the bot",
  "onboarding.status": "{statuses}",
  "onboarding.consent_title": "Before we start",
  "onboarding.consent_1": "<b>Your chat with me never appears in the shared group.</b> But {admin} runs the bot and can technically read it.",
  "onboarding.consent_2": "<b>Google's free tier:</b> Google staff may read the conversation.",
  "onboarding.consent_3": "<b>Only what you explicitly approve goes to the shared chat.</b>",
  "onboarding.consent_4": "<b>I'm not a therapist.</b> If things become unsafe, I'll share where to get help.",
  "onboarding.consent_retention": "The verbatim text of our chat is kept for up to 7 days; after that only a short summary remains.",
  "onboarding.consent_accept": "I agree",
  "onboarding.consent_decline": "Not now",
  "onboarding.declined": "Okay. If you change your mind — /start",
  "onboarding.ready": "All set. I'll reply when you pause.",
  "onboarding.ready_example_1": "I translate what you write to each other if you use different languages.",
  "onboarding.ready_example_2": "I help when the conversation gets tense.",
  "onboarding.ready_example_3": "In our private chat I'll help you phrase what's hard to say.",
  "onboarding.start_talk": "Start talking",
  "onboarding.setup_translation": "Set up translation",
  "onboarding.consent_translation_pending": "Translation coming later.",

  "check.ask_paraphrase": "Reply to this message in your own words: what did you hear?",
  "check.skip_button": "Skip",
  "check.skipped": "Okay, back to the conversation.",
  "check.reply_hint": "Please reply to my message.",
  "check.understood_button": "I was understood",
  "check.clarify_button": "Clarify meaning",
  "check.clarify": "Write what you meant — I'll ask for another paraphrase.",
  "check.success": "Thank you. The meaning got through.",
  "check.discuss_more": "Looks like there's more to talk through here.",
  "check.cooldown": "You can repeat the exercise in {minutes} min.",
  "check.already_active": "The exercise is already running.",
  "check.timeout": "The exercise ended: no reply for a while.",
  "check.cancelled": "Exercise stopped.",
  "check.offer_button": "Check what was heard",

  "button.not_yours": "This button is for {name}",
  "button.stale": "This is no longer relevant.",

  "fallback.pause": "I can't reply right now. Try taking turns retelling what you heard in your own words.",
  "fallback.dm": "I can't reply right now. Try writing down what hurt you — we'll come back to it later.",
  "fallback.urgent_help": "Urgent help: /help",
  "fallback.neutral_block": "I can't process this message.",
  "quota.level_70": "Today's model limit is almost used up: short voice summaries are off until {reset}.",
  "quota.level_90": "Translation and the mediator are off until {reset}. Direct chats still work.",
  "quota.restored": "The limit has reset: translation and the mediator are back.",

  "voice.not_recognized": "I couldn't transcribe this voice message. Could you type it?",
  "voice.not_transcribed": "voice message not transcribed",
  "voice.summary_label": "In short",

  "draft.unknown_delivery": "I couldn't confirm delivery. Check the group before sending again.",
  "draft.failed_delivery": "The message wasn't sent. The draft is saved, you can try again.",
  "draft.send_button": "Send to the group",
  "draft.edit_button": "Edit text",
  "draft.delete_button": "Delete",
  "draft.compose_button": "Phrase it for partner",
  "draft.header": "✉ {name} (phrased with the bot's help)",
  "notes.offer": "I'll be able to use this note in replies to both of you. Your partner may infer its meaning from those replies.",
  "notes.allow_button": "Allow in shared replies",
  "notes.edit_button": "Edit",
  "notes.deny_button": "Don't allow",
  "notes.empty": "No shared notes yet. They only appear after you explicitly allow them.",

  "safety.neutral_first_line": "Message from the assistant",
  "safety.group_line": "Let's pause here. Help resources are in your direct chats and in /help.",
  "safety.pack_intro": "If things feel hard or unsafe right now, these people can help:",

  "menu.compose": "Prepare a message",
  "menu.notes": "My notes",
  "menu.data": "Data and access",
  "menu.help": "Help",
  "menu.resume": "Resume",
  "menu.irreversible": "This can't be undone.",
};
