// Fixed texts, English. Same keys as ru.js; English is also the source for
// machine translation into other languages (DR15) and the fallback when that
// translation fails.

export default {
  "state.paused": "The bot is paused: new group messages are not stored or processed. Direct chats still work.",
  "state.resume_not_pauser": "Only the person who paused can resume.",
  "state.resumed": "Pause lifted. I'm following the conversation again.",
  "state.revoked": "Consent withdrawn, the bot has stopped. Data is kept but not processed.",
  "state.revoked_partner_dm": "Until consent is restored, I only use our own chat — I'm not using the shared history right now.",
  "state.suspended_third_member": "Someone new joined the group. I've stopped: the shared conversation should stay between the two of you.",
  "state.suspended_not_admin": "I need admin rights to check that only the two of you are in the group. Give them back and I'll continue.",
  "state.restored": "It's just the two of you again. Continuing.",
  "state.stranger_start": "This is a private bot for one couple.",

  "onboarding.admin_request": "I need admin rights to see all messages and check that only the two of you are here. I won't delete or ban anyone.",
  "onboarding.group_intro": "I help you translate and take turns talking. I'll start once each of you agrees.",
  "onboarding.open_bot_button": "{name} → open the bot",
  "onboarding.status": "{statuses}",
  "onboarding.pick_language": "Which language is most comfortable for you?",
  "onboarding.pick_country": "Which country do you live in? I need it to give local help contacts if ever needed.",
  "onboarding.other_country_button": "Another country",
  "onboarding.country_hint": "Type the name of the country.",
  "onboarding.bad_country": "I didn't recognise the country. Type its name again, for example \"Spain\".",
  "onboarding.ask_time": "What time is it for you now? Type it like 14:30 — so I can name times in your time zone.",
  "onboarding.bad_time": "I didn't get the time. Type it like 14:30.",
  "onboarding.need_two": "Only the two of you and me should be in the group.",
  "onboarding.not_in_group": "You need to be in the group where I work first.",
  "onboarding.couple_full": "This couple already has two members.",
  "onboarding.other_couple": "You're already part of another couple.",
  "onboarding.open_bot": "Open the bot",
  "onboarding.consent_title": "Before we start",
  "onboarding.consent_1": "<b>Your chat with me never appears in the shared group.</b> But {admin} runs the bot and can technically read it.",
  "onboarding.consent_2": "<b>Google's free tier:</b> Google staff may read the conversation.",
  "onboarding.consent_3": "<b>Only what you explicitly approve goes to the shared chat.</b>",
  "onboarding.consent_4": "<b>I'm not a therapist.</b> If things become unsafe, I'll share where to get help.",
  "onboarding.consent_retention": "The verbatim text of our chat is kept for up to 7 days; after that only a short summary remains.",
  "onboarding.consent_accept": "I agree",
  "onboarding.consent_decline": "Not now",
  "onboarding.declined": "Okay. If you change your mind — /start",
  "onboarding.ready": "All set. I'll reply when you pause.",
  "onboarding.ready_example_1": "I translate what you write to each other if you use different languages.",
  "onboarding.ready_example_2": "I help when the conversation gets tense.",
  "onboarding.ready_example_3": "In our private chat I'll help you phrase what's hard to say.",
  "onboarding.start_talk": "Start talking",
  "onboarding.setup_translation": "Set up translation",
  "onboarding.consent_translation_pending": "Translation coming later.",

  "check.ask_paraphrase": "Reply to this message in your own words: what did you hear?",
  "check.skip_button": "Skip",
  "check.skipped": "Okay, back to the conversation.",
  "check.reply_hint": "Please reply to my message.",
  "check.understood_button": "I was understood",
  "check.clarify_button": "Clarify meaning",
  "check.clarify": "Write what you meant — I'll ask for another paraphrase.",
  "check.success": "Thank you. The meaning got through.",
  "check.discuss_more": "Looks like there's more to talk through here.",
  "check.cooldown": "You can repeat the exercise in {minutes} min.",
  "check.already_active": "The exercise is already running.",
  "check.timeout": "The exercise ended: no reply for a while.",
  "check.cancelled": "Exercise stopped.",
  "check.offer_button": "Check what was heard",

  "button.not_yours": "This button is for {name}",
  "button.stale": "This is no longer relevant.",

  "fallback.pause": "I can't reply right now. Try taking turns retelling what you heard in your own words.",
  "fallback.dm": "I can't reply right now. Try writing down what hurt you — we'll come back to it later.",
  "fallback.urgent_help": "Urgent help: /help",
  "fallback.neutral_block": "I can't process this message.",
  "quota.level_70": "Today's model limit is almost used up: short voice summaries are off until {reset}.",
  "quota.level_90": "Translation and the mediator are off until {reset}. Direct chats still work.",
  "quota.restored": "The limit has reset: translation and the mediator are back.",

  "voice.not_recognized": "I couldn't transcribe this voice message. Could you type it?",
  "voice.not_transcribed": "voice message not transcribed",
  "voice.summary_label": "In short",
  "voice.quota": "I can't transcribe right now: the daily model limit is used up.",
  "voice.transcript_file": "The transcript is long — attaching it as a file.",

  "draft.unknown_delivery": "I couldn't confirm delivery. Check the group before sending again.",
  "draft.failed_delivery": "The message wasn't sent. The draft is saved, you can try again.",
  "draft.send_button": "Send to the group",
  "draft.edit_button": "Edit text",
  "draft.delete_button": "Delete",
  "draft.compose_button": "Phrase it for partner",
  "draft.header": "✉ {name} (phrased with the bot's help)",
  "draft.ask_text": "What do you want to tell your partner? Write it as it is — I'll help phrase it.",
  "draft.ask_edit": "What should I change in the text?",
  "draft.meaning_label": "Meaning for you",
  "draft.deleted": "Draft deleted.",
  "draft.sent": "Sent to the group.",
  "draft.not_active": "I can't send to the group right now: the bot isn't active there.",
  "draft.failed": "I couldn't phrase it. Try again a bit later.",
  "notes.allowed": "The note is allowed in shared replies. To withdraw it — /notes.",
  "notes.denied": "Okay, I won't keep the note.",
  "notes.edit_hint": "Write how the note should read.",
  "notes.list_title": "Your notes for shared replies:",
  "notes.revoke_button": "Withdraw",
  "notes.revoked": "The note is withdrawn and no longer used. Replies already posted in the group stay.",
  "notes.offer": "I'll be able to use this note in replies to both of you. Your partner may infer its meaning from those replies.",
  "notes.allow_button": "Allow in shared replies",
  "notes.edit_button": "Edit",
  "notes.deny_button": "Don't allow",
  "notes.empty": "No shared notes yet. They only appear after you explicitly allow them.",

  "safety.neutral_first_line": "Message from the assistant",
  "safety.group_line": "Let's pause here. Help resources are in your direct chats and in /help.",
  "safety.pack_intro": "If things feel hard or unsafe right now, these people can help:",

  "help.group": "I help you talk and understand each other. I reply when you pause. Commands: /check — check what was heard; /pause — pause; /translate — turn translation on or off.",
  "translate.on": "Translation is on.",
  "translate.off": "Translation is off. Turn it back on — /translate.",
  "state.not_active": "I'm not leading the group conversation right now.",
  "cmd.help": "How I work and where to get help",
  "cmd.pause": "Pause the bot",
  "cmd.translate": "Turn translation on or off",
  "cmd.menu": "Menu",
  "cmd.draft": "Phrase a message to your partner",
  "cmd.notes": "My notes",
  "cmd.resume": "Resume",
  "menu.title": "What shall we do?",
  "menu.back": "Back",
  "data.title": "Data and access",
  "data.forget": "Delete my chat",
  "data.forget_group": "Delete shared history",
  "data.revoke": "Withdraw consent",
  "data.consent": "Restore consent",
  "data.flag_clear": "Clear my mark",
  "data.pause": "Pause",
  "data.forget_confirm": "This will delete: our chat, drafts, your notes and the short summary of our conversation.",
  "data.forget_group_confirm": "This will delete: the whole shared group history and its summary. Your partner will see a notice in the group.",
  "data.revoke_confirm": "The bot will stop working for both of you until you restore consent. Data is kept but not processed.",
  "data.confirm_button": "Yes, do it",
  "data.cancel_button": "Cancel",
  "data.cancelled": "Okay, nothing changed.",
  "data.forget_done": "Done: chat, drafts and notes deleted.",
  "data.forget_group_done": "Done: shared history deleted.",
  "data.forget_group_notice": "The shared history was deleted at the request of one of you.",
  "data.revoke_done": "Consent withdrawn. To restore — /consent.",
  "data.consent_done": "Consent restored.",
  "data.flag_clear_done": "Mark cleared.",
  "data.flag_clear_none": "Nothing to clear.",
  "data.only_consent_forget": "While consent is withdrawn, I only respond to /consent and /forget.",
  "data.anonymity_warning": "Your partner will understand it was you. Continue?",
  "menu.compose": "Prepare a message",
  "menu.notes": "My notes",
  "menu.data": "Data and access",
  "menu.help": "Help",
  "menu.resume": "Resume",
  "menu.irreversible": "This can't be undone.",
};
